apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: pycsw
spec:
  host: {{ .Values.pycsw.config.server.host }}
  #host: https://pycsw-udpkatalog-dev.apps.capk.muenchen.de
  port:
    targetPort: http
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: pycsw
    weight: 100
  wildcardPolicy: None
