apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Values.global.namespace }}
  labels:
    io.kompose.service: {{ .Values.pycsw.name }}
  name: {{ .Values.pycsw.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: {{ .Values.pycsw.name }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.service: {{ .Values.pycsw.name }}
    spec:
      containers:
      - env:
        - name: PYCSW_SERVER_URL
          value: {{ .Values.pycsw.config.server.url }}
        - name: PYCSW_REPOSITORY_DATABASE_URI
          value: {{ .Values.pycsw.config.repository.database }}
        image: {{ .Values.pycsw.image }}
        name: {{ .Values.pycsw.name }}
        ports:
        - containerPort: {{ .Values.pycsw.container_port }}
        resources: {{- toYaml .Values.pycsw.resources | nindent 12 }}
        volumeMounts:
        - mountPath: {{ .Values.pycsw.volume_path }}
          name: {{ .Values.pycsw.volume_name }}
        - mountPath: {{ .Values.pycsw.datashare_volume_path }}
          name: {{ .Values.pycsw.datashare_volume_name }}
        - mountPath: /home/pycsw/pycsw/pycsw/core/metadata.py
          subPath: metadata.py
          name: pycsw-metadata-py-volume
        securityContext: {}
        

      restartPolicy: Always
      volumes:
      - name: {{ .Values.pycsw.volume_name }}
        configMap:
          name: {{ .Values.pycsw.configmap_name }}
      - name: {{ .Values.pycsw.datashare_volume_name }}
        persistentVolumeClaim:
          claimName: {{ .Values.pycsw.datashare_claim_name }}
      - name: pycsw-metadata-py-volume
        configMap:
          name: pycsw-metadata-py
